name: Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn install

      - name: Build dynamic-router
        run: yarn build:dynamic-router
      - name: Publish dynamic-router
        run: cd dist/dynamic-router && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Build flex
        run: yarn build:flex
      - name: Publish flex
        run: cd dist/flex && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Build helpers
        run: yarn build:helpers
      - name: Publish helpers
        run: cd dist/helpers && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Build material-components-web
        run: yarn build:material-components-web
      - name: Publish material-components-web
        run: cd dist/material-components-web && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Build suspense
        run: yarn build:suspense
      - name: Publish suspense
        run: cd dist/suspense && npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
